spring:

  data:
    mongodb:
      uri: mongodb://localhost:27017/ai-recommendations-fitness-db
      database: ai-recommendations-fitness-db

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # Use ErrorHandlingDeserializer as the main deserializer
      #value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.ai_service.model.Activity
        spring.json.trusted.packages: "*"
        #spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        # Tell Jackson where your model lives
        #spring.json.trusted.packages: "com.fitness.ai_service.model"

kafka:
  topic:
    name: activity-events

gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083